name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install C++ Dependencies
        run: sudo apt-get install g++

      - name: "Make Ryan's Assignment Copy"
        run: |
          cd ryan
          echo "Making the game..."
          make
          echo "Making the tests..."
          make test.exe
          echo "TODO: Run Tests..."
